services:
  web:
    build:
      context: docker/web
      dockerfile: Dockerfile
    working_dir: /web
    volumes:
      - ./web:/web
      - /web/node_modules/
    ports:
      - "127.0.0.1:8080:5173"

  orders-http:
    build:
      context: docker/app
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - ./internal:/internal
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
    working_dir: /internal
    ports:
      - "127.0.0.1:3031:$PORT"
    env_file:
      - .env
    environment:
      SERVICE: orders
      SERVER_TO_RUN: http
      GOCACHE: /go-cache
    depends_on:
      postgres_db:
        condition: service_healthy
  inventory-http:
    build:
      context: docker/app
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - ./internal:/internal
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
    working_dir: /internal
    ports:
      - "127.0.0.1:3032:$PORT"
    env_file:
      - .env
    environment:
      SERVICE: inventory
      SERVER_TO_RUN: http
      GOCACHE: /go-cache
    depends_on:
      postgres_db:
        condition: service_healthy
  postgres_db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: