services:
  web:
    build:
      context: docker/web
      dockerfile: Dockerfile
    working_dir: /web
    volumes:
      - ./web:/web
      - /web/node_modules/
    ports:
      - "127.0.0.1:8080:5173"

  orders-http:
    build:
      context: docker/app
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - ./internal:/internal
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
    working_dir: /internal
    ports:
      - "127.0.0.1:3031:$PORT"
    env_file:
      - .env
    environment:
      SERVICE: orders
      SERVER_TO_RUN: http
      GOCACHE: /go-cache
    depends_on:
      postgres_db:
        condition: service_healthy
      kafka:
        condition: service_started
  inventory-http:
    build:
      context: docker/app
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - ./internal:/internal
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
    working_dir: /internal
    ports:
      - "127.0.0.1:3032:$PORT"
    env_file:
      - .env
    environment:
      SERVICE: inventory
      SERVER_TO_RUN: http
      GOCACHE: /go-cache
    depends_on:
      postgres_db:
        condition: service_healthy
      kafka:
        condition: service_started
  postgres_db:
    image: postgis/postgis:15-3.3-alpine
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.8.0
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,EXTERNAL://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      CLUSTER_ID: 'ZTIzM2FhMTE0Yjg4NGVlZT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8081:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
    depends_on:
      - kafka
volumes:
  postgres_data:
  kafka_data: