// Package orders provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package orders

import (
	"time"
)

// Defines values for OrderStatus.
const (
	Cancelled OrderStatus = "cancelled"
	Completed OrderStatus = "completed"
	Confirmed OrderStatus = "confirmed"
	Delivered OrderStatus = "delivered"
	Pending   OrderStatus = "pending"
	Shipped   OrderStatus = "shipped"
)

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
	Slug    string `json:"slug"`
}

// LineItem defines model for LineItem.
type LineItem struct {
	LineTotal   float32 `json:"lineTotal"`
	LineWeight  float32 `json:"lineWeight"`
	ProductName string  `json:"productName"`
	ProductUUID *string `json:"productUUID,omitempty"`
	Quantity    int     `json:"quantity"`
	UnitPrice   float32 `json:"unitPrice"`
	UnitWeight  float32 `json:"unitWeight"`
}

// Order defines model for Order.
type Order struct {
	CompletedDate *time.Time  `json:"completedDate"`
	DeliveredDate *time.Time  `json:"deliveredDate"`
	Destination   string      `json:"destination"`
	LineItems     []LineItem  `json:"lineItems"`
	OrderTotal    float32     `json:"orderTotal"`
	OrderUUID     *string     `json:"orderUUID,omitempty"`
	OrderedDate   *time.Time  `json:"orderedDate,omitempty"`
	PlacedBy      string      `json:"placedBy"`
	ShippedDate   *time.Time  `json:"shippedDate"`
	Status        OrderStatus `json:"status"`
	Weight        float32     `json:"weight"`
}

// OrderStatus defines model for Order.Status.
type OrderStatus string

// Orders defines model for Orders.
type Orders struct {
	Orders []Order `json:"orders"`
}

// GetOrdersParams defines parameters for GetOrders.
type GetOrdersParams struct {
	DateFrom *time.Time `form:"dateFrom,omitempty" json:"dateFrom,omitempty"`
	DateTo   *time.Time `form:"dateTo,omitempty" json:"dateTo,omitempty"`
}

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody = Order
