// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package ports

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
	Slug    string `json:"slug"`
}

// Location defines model for Location.
type Location struct {
	Address      string     `json:"address"`
	City         string     `json:"city"`
	CreatedAt    *time.Time `json:"createdAt,omitempty"`
	LocationUUID *string    `json:"locationUUID,omitempty"`
	Name         string     `json:"name"`
	UpdatedAt    *time.Time `json:"updatedAt,omitempty"`
}

// Locations defines model for Locations.
type Locations struct {
	Locations []Location `json:"locations"`
}

// Product defines model for Product.
type Product struct {
	CreatedAt   *time.Time `json:"createdAt,omitempty"`
	Name        string     `json:"name"`
	Price       float32    `json:"price"`
	ProductUUID *string    `json:"productUUID,omitempty"`
	UpdatedAt   *time.Time `json:"updatedAt,omitempty"`
	Weight      float32    `json:"weight"`
}

// ProductStock defines model for ProductStock.
type ProductStock struct {
	CreatedAt   *time.Time `json:"createdAt,omitempty"`
	Name        string     `json:"name"`
	Price       float32    `json:"price"`
	ProductUUID *string    `json:"productUUID,omitempty"`
	Quantity    int        `json:"quantity"`
	UpdatedAt   *time.Time `json:"updatedAt,omitempty"`
	Weight      float32    `json:"weight"`
}

// ProductStocks defines model for ProductStocks.
type ProductStocks struct {
	Items *[]ProductStock `json:"items,omitempty"`
}

// Products defines model for Products.
type Products struct {
	Items *[]Product `json:"items,omitempty"`
}

// AddProductsToLocationJSONBody defines parameters for AddProductsToLocation.
type AddProductsToLocationJSONBody = []struct {
	ProductUUID openapi_types.UUID `json:"productUUID"`
	Quantity    int                `json:"quantity"`
}

// TransferProductsJSONBody defines parameters for TransferProducts.
type TransferProductsJSONBody struct {
	DestinationLocationUUID openapi_types.UUID `json:"destinationLocationUUID"`
	Products                []struct {
		ProductUUID openapi_types.UUID `json:"productUUID"`
		Quantity    int                `json:"quantity"`
	} `json:"products"`
	SourceLocationUUID openapi_types.UUID `json:"sourceLocationUUID"`
}

// CreateLocationJSONRequestBody defines body for CreateLocation for application/json ContentType.
type CreateLocationJSONRequestBody = Location

// UpdateLocationJSONRequestBody defines body for UpdateLocation for application/json ContentType.
type UpdateLocationJSONRequestBody = Location

// AddProductsToLocationJSONRequestBody defines body for AddProductsToLocation for application/json ContentType.
type AddProductsToLocationJSONRequestBody = AddProductsToLocationJSONBody

// CreateProductJSONRequestBody defines body for CreateProduct for application/json ContentType.
type CreateProductJSONRequestBody = Product

// TransferProductsJSONRequestBody defines body for TransferProducts for application/json ContentType.
type TransferProductsJSONRequestBody TransferProductsJSONBody

// UpdateProductJSONRequestBody defines body for UpdateProduct for application/json ContentType.
type UpdateProductJSONRequestBody = Product
