// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package ports

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
	Slug    string `json:"slug"`
}

// Location defines model for Location.
type Location struct {
	Address      string  `json:"address"`
	City         string  `json:"city"`
	LocationUUID *string `json:"locationUUID,omitempty"`
	Name         string  `json:"name"`
}

// Locations defines model for Locations.
type Locations struct {
	Locations []Location `json:"locations"`
}

// Product defines model for Product.
type Product struct {
	AvailableQuantity int     `json:"availableQuantity"`
	ItemUUID          *string `json:"itemUUID,omitempty"`
	LocationUUID      string  `json:"locationUUID"`
	Name              string  `json:"name"`
	Price             float32 `json:"price"`
	Weight            float32 `json:"weight"`
}

// Products defines model for Products.
type Products struct {
	Items *[]Product `json:"items,omitempty"`
}

// TransferProductsJSONBody defines parameters for TransferProducts.
type TransferProductsJSONBody struct {
	DestinationLocationUUID openapi_types.UUID `json:"destinationLocationUUID"`
	Products                []struct {
		ProductUUID openapi_types.UUID `json:"productUUID"`
		Quantity    int                `json:"quantity"`
	} `json:"products"`
	SourceLocationUUID openapi_types.UUID `json:"sourceLocationUUID"`
}

// CreateLocationJSONRequestBody defines body for CreateLocation for application/json ContentType.
type CreateLocationJSONRequestBody = Location

// TransferProductsJSONRequestBody defines body for TransferProducts for application/json ContentType.
type TransferProductsJSONRequestBody TransferProductsJSONBody
