// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package ports

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for OrderStatus.
const (
	Cancelled OrderStatus = "cancelled"
	Completed OrderStatus = "completed"
	Confirmed OrderStatus = "confirmed"
	Delivered OrderStatus = "delivered"
	Pending   OrderStatus = "pending"
	Shipped   OrderStatus = "shipped"
)

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
	Slug    string `json:"slug"`
}

// LineItem defines model for LineItem.
type LineItem struct {
	LineTotal   float32            `json:"lineTotal"`
	LineWeight  float32            `json:"lineWeight"`
	ProductName string             `json:"productName"`
	ProductUUID openapi_types.UUID `json:"productUUID"`
	Quantity    int                `json:"quantity"`
	UnitPrice   float32            `json:"unitPrice"`
	UnitWeight  float32            `json:"unitWeight"`
}

// Order defines model for Order.
type Order struct {
	CompletedDate *time.Time         `json:"completedDate"`
	DeliveredDate *time.Time         `json:"deliveredDate"`
	LineItems     []LineItem         `json:"lineItems"`
	OrderTotal    float32            `json:"orderTotal"`
	OrderUUID     openapi_types.UUID `json:"orderUUID"`
	OrderedDate   *time.Time         `json:"orderedDate,omitempty"`
	ShippedDate   *time.Time         `json:"shippedDate"`
	Status        OrderStatus        `json:"status"`
	Weight        float32            `json:"weight"`
}

// OrderStatus defines model for Order.Status.
type OrderStatus string

// Orders defines model for Orders.
type Orders struct {
	Trainings *[]Order `json:"trainings,omitempty"`
}

// GetOrdersParams defines parameters for GetOrders.
type GetOrdersParams struct {
	DateFrom time.Time `form:"dateFrom" json:"dateFrom"`
	DateTo   time.Time `form:"dateTo" json:"dateTo"`
}

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody = Order
